### ISSUE TITLE
feat: hidden friends

### ISSUE THREAD

**Issue by TheMoonld** [rhunk/SnapEnhance#773] opened 2024-03-25 13:41 UTC
### Description

Feature to hide friends from friend list. You could access them from a secret menu

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment] 2024-03-26 06:28
Duplicate of https://github.com/rhunk/SnapEnhance/issues/335

**Closed by rhunk** 2024-03-26 06:28 UTC
Labels: enhancement
