### ISSUE TITLE
Suspicious activities 

### ISSUE THREAD

**Issue by OctavXD** [rhunk/SnapEnhance#631] opened 2024-01-28 17:05 UTC
### Description

Patched the app (newest version for all apps) and it says it cannot log in due to suspicious activity 

### Reproduction steps

Patched the app
Tried to login on the account 
Suspicious activities detected 

### Logs

```markdown
No logs
```

### Snapchat Version

Newest 

### SnapEnhance Version

Newest 

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by sestuff** [comment] 2024-01-28 17:46
Duplicate of #544

**Closed** 2024-01-28 19:17 UTC
Labels: bug
