### ISSUE TITLE
Images sent to story are cropped on the edges

### ISSUE THREAD

**Issue by jonahbebko** [rhunk/SnapEnhance#640] opened 2024-01-29 12:33 UTC
### Description

As title describes. Any image added to story is slightly cropped on the edges. Not a camera setting which causes this - I've disabled every camera setting I could and tried this test image multiple times. Disabling module in LSPosed fixes issue.

Uploaded is a screenshot of the image before I uploaded it, in Snapchat's image editor, and then a screenshot of the resulting story post.

![Screenshot_20240129-072231](https://github.com/rhunk/SnapEnhance/assets/38584503/8d2de996-231d-427b-93ae-647668fafa16)
![Screenshot_20240129-072241](https://github.com/rhunk/SnapEnhance/assets/38584503/9d4e4d2d-2642-4095-b8f2-fc6bc5403d9b)

### Reproduction steps

1. Take a picture, and add a caption which spans the entire line.
2. Upload to story.
3. View story. Text is cropped.

### Snapchat Version

12.72.0.35 Beta

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment] 2024-01-29 14:47
Disable Immersive Camera Preview

**Comment by authorisation** [comment] 2024-01-29 14:51
Also, duplicate of #341

**Closed by authorisation** 2024-01-29 14:51 UTC
Labels: bug
