### ISSUE TITLE
Snapchat cant connect to the snapenhance app

### ISSUE THREAD

**Issue by halamadrid47** [rhunk/SnapEnhance#922] opened 2024-04-17 18:05 UTC
### Description

If i open snapchat than a problem comes up. (Patched properly)
![IMG_20240413_182150_751](https://github.com/rhunk/SnapEnhance/assets/99083228/3a1b73f6-ff57-4b93-851b-757ebba82f2b)

### Reproduction steps

.

### Logs

```markdown
Failed to find ANDROID_ACTION_MENU_V2 in ConfigRule
```

### Snapchat Version

12.82.0.51

### SnapEnhance Version

2.0.1 (stable)

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by bocajthomas** [comment] 2024-04-18 01:09
duplicate of #875

**Closed** 2024-04-18 01:10 UTC
Labels: bug, invalid
