### ISSUE TITLE
Snapchat Not working

### ISSUE THREAD

**Issue by Modcal** [rhunk/SnapEnhance#890] opened 2024-04-12 19:50 UTC
### Description

Today the issue has started
the Snapchat is not working and a message of force close the same for snap enhance 2.0
Even after I reinstalled 1.2.6 the same issue remain the picture stock in. Snapchat logo then a message of closing the app

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Logs

```markdown
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{me.rhunk.snapenhance/me.rhunk.snapenhance.ui.download.DownloadManagerActivity}: java.lang.ClassNotFoundException: Didn't find class "me.rhunk.snapenhance.ui.download.DownloadManagerActivity" on path: DexPathList[[zip file "/data/app/~~t3NAS9RVOMPvNGg5K5gF4w==/me.rhunk.snapenhance-j1P79_2a0LZpyDow09SEcA==/base.apk"],nativeLibraryDirectories=[/data/app/~~t3NAS9RVOMPvNGg5K5gF4w==/me.rhunk.snapenhance-j1P79_2a0LZpyDow09SEcA==/lib/arm64, /data/app/~~t3NAS9RVOMPvNGg5K5gF4w==/me.rhunk.snapenhance-j1P79_2a0LZpyDow09SEcA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
```

### Snapchat Version

12.80

### SnapEnhance Version

2.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment] 2024-04-12 20:02
Duplicate of #886

**Comment by bocajthomas** [comment] 2024-04-12 20:03
@authorisation ban/restrict him ? 
He's opened this 3 times now

**Closed by bocajthomas** 2024-04-12 20:02 UTC
Labels: bug, duplicate, invalid

**Comment by Modcal** [comment] 2024-04-12 20:11
> Duplicate of #886

Can you please support
