### ISSUE TITLE
Text in snaps not showing up

### ISSUE THREAD

**Issue by ItsJustDB** [rhunk/SnapEnhance#708] opened 2024-02-28 01:58 UTC
### Description

When taking a snap using the following options; any sort of filter, the useage of front flash or quick reply (double tapping to snap reply) it does not allow you to send text within the snap itself as when the recipient recieves it the snap will come up with no text and only of whatever the snap you have taken was. However if you send a snap without using those of the following and have text within the snap and manually select the recipients they will see the text.

### Reproduction steps

1. Taking a snap using the following and/or; front flash, filter, quick reply
2. Typing in within the snap or drawing or stickers.
3. Recipient will not recieve the snap with any of the extras other than the original image of the snap

### Snapchat Version

12.70.0.34 and above

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment] 2024-02-28 09:40
Duplicate of https://github.com/rhunk/SnapEnhance/issues/303

**Closed by rhunk** 2024-02-28 09:40 UTC
Labels: bug
