### ISSUE TITLE
Random packagename...

### ISSUE THREAD

**Issue by JaKrIvMa** [rhunk/SnapEnhance#1142] opened 2024-06-14 19:05 UTC
### Description

Like magisk to hide packagen name.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by RSR1337** [comment] 2024-06-14 23:20
> ### Description
> Like magisk to hide packagen name.
> 
> ### Agreement
> * [x]  There is no issue already suggesting my feature.

It's already There, use manager

**Comment by JaKrIvMa** [comment] 2024-06-15 05:13
> > ### Description
> > Like magisk to hide packagen name.
> > ### Agreement
> > 
> > * [x]   There is no issue already suggesting my feature.
> 
> It's already There, use manager

Where in manager is this?😃

**Comment by authorisation** [comment] 2024-06-15 10:11
Duplicate of #21

**Closed** 2024-06-15 10:11 UTC
Labels: enhancement
