### ISSUE TITLE
feat: Option to remove drawings/markups

### ISSUE THREAD

**Issue by holidayhares** [rhunk/SnapEnhance#761] opened 2024-03-21 21:33 UTC
### Description

An option to remove drawings or any markups from any recieved snap or story that you are viewing. Obviously only for your view, and you would be able to toggle the drawings on/off. No idea if this is easy or even possible to implement lol, I'm a rookie around here.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment] 2024-03-22 08:36
Duplicate of https://github.com/rhunk/SnapEnhance/issues/431

**Closed** 2024-03-22 08:36 UTC
Labels: enhancement
