### ISSUE TITLE
bug: - show chat messages not working with reply button enabled

### ISSUE THREAD

**Issue by abadi718** [rhunk/SnapEnhance#43] opened 2023-06-05 14:35 UTC
### Description

There is an error with show chat messages. when I enable show chat messages and reply button then it will not show the messages in the notifications. So I have to disable the reply button to see messages in notifications.

### Snapchat Version

12.36.0.53

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] There is no issue already describing my problem.

**Comment by authorisation** [comment] 2023-06-05 22:36
Cannot reproduce, wontfix.

**Closed by authorisation** 2023-06-05 22:36 UTC
Labels: bug
