### ISSUE TITLE
Ffmpeg  or merge issue?

### ISSUE THREAD

**Issue by JaKrIvMa** [rhunk/SnapEnhance#656] opened 2024-02-05 23:51 UTC
### Description

On videos that are being processed, some fails, some get saved.

On public stories it happens most of the time not so much on private.

Stickers and url in videos

Seen logs but no good info there.

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Logs

```markdown
No relevant logs.

|V/2024-02-06 00:42:01/manager/Loading RemoteSideContext
|W/2024-02-06 00:42:01/manager/Failed to get scripts folder
|W/2024-02-06 00:42:01/manager/Failed to get scripts folder
|V/2024-02-06 00:42:01/core/reloading config
|V/2024-02-06 00:42:01/manager/Syncing remote took 2 ms
|V/2024-02-06 00:42:02/core/database xxx.xxx integrity check passed
|V/2024-02-06 00:42:02/core/database xxx.xxx integrity check passed
|V/2024-02-06 00:42:02/core/feature manager init took 96 ms
|W/2024-02-06 00:42:03/manager/Failed to get scripts folder
|V/2024-02-06 00:42:03/core/init took 1683ms
|D/2024-02-06 00:55:38/core/received message type: story_notification_received
|D/2024-02-06 00:55:39/core/received message type: story_notification_received
|D/2024-02-06 00:55:39/core/received message type: story_notification_received
|D/2024-02-06 00:55:39/core/received message type: story_notification_received
|D/2024-02-06 00:55:39/core/received message type: story_notification_received
|V/2024-02-06 01:00:38/core/feature manager onActivityCreate took 56 ms
|V/2024-02-06 01:00:38/core/onActivityCreate took 56
|V/2024-02-06 01:00:38/core/Loaded 20 cached messages in 138ms
|I/2024-02-06 01:00:40/FA/App measurement disabled via the manifest
|I/2024-02-06 01:00:40/FA/App measurement initialized, version: 82083
|I/2024-02-06 01:00:40/FA/To enable debug logging run: adb shell setprop xxx.xxx VERBOSE
|I/2024-02-06 01:00:40/FA/To enable faster debug mode event logging run:
  adb shell setprop xxx.xxx xxx.xxx
|V/2024-02-06 01:01:05/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:02:56/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:39/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:59/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:59/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:59/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:03:59/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|V/2024-02-06 01:04:13/manager/trigger sync for friend xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
|D/2024-02-06 01:04:18/SnapEnhanceCommon/Starting http server on port 21266
|D/2024-02-06 01:04:18/manager/downloading media
|D/2024-02-06 01:04:18/SnapEnhanceCommon/[http-server:21266] GET /4c5dd619955
|V/2024-02-06 01:04:18/manager/downloaded 1 medias
|V/2024-02-06 01:04:19/manager/download complete
|V/2024-02-06 01:04:19/core/onSuccess: outputFile=xxx.xxx
|D/2024-02-06 01:04:25/manager/downloading media
|D/2024-02-06 01:04:25/SnapEnhanceCommon/[http-server:21266] GET /4c797ee606c
|V/2024-02-06 01:04:25/manager/downloaded 1 medias
|V/2024-02-06 01:04:26/manager/download complete
|V/2024-02-06 01:04:26/core/onSuccess: outputFile=xxx.xxx
|D/2024-02-06 01:04:27/manager/downloading media
|D/2024-02-06 01:04:27/SnapEnhanceCommon/[http-server:21266] GET /4c7df22cef5
|V/2024-02-06 01:04:27/manager/downloaded 1 medias
|V/2024-02-06 01:04:27/manager/download complete
|V/2024-02-06 01:04:27/core/onSuccess: outputFile=xxx.xxx
|D/2024-02-06 01:04:36/core/received message type: snap
|D/2024-02-06 01:04:37/SnapEnhanceCommon/http server closed due to timeout
|D/2024-02-06 01:04:37/SnapEnhanceCommon/http server timed out
|V/2024-02-06 01:04:42/manager/Loading RemoteSideContext
|W/2024-02-06 01:04:42/manager/Failed to get scripts folder
|W/2024-02-06 01:04:42/manager/Failed to get scripts folder
|V/2024-02-06 01:04:42/core/reloading config
|V/2024-02-06 01:04:42/manager/Syncing remote took 3 ms
|V/2024-02-06 01:04:42/core/database xxx.xxx integrity check passed
|V/2024-02-06 01:04:43/core/database xxx.xxx integrity check passed
|V/2024-02-06 01:04:43/core/feature manager init took 23 ms
|W/2024-02-06 01:04:43/manager/Failed to get scripts folder
|V/2024-02-06 01:04:43/core/init took 274ms
```

### Snapchat Version

12.71.0.30

### SnapEnhance Version

V2.0.0 latest cI build

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment] 2024-02-06 10:11
Duplicate of https://github.com/rhunk/SnapEnhance/issues/319

**Closed by rhunk** 2024-02-06 10:11 UTC
Labels: bug
