### ISSUE TITLE
Log in not working anymore 

### ISSUE THREAD

**Issue by CaliberZero** [rhunk/SnapEnhance#625] opened 2024-01-27 14:30 UTC
### Description

As of the new update of Snapchat itself it's not allowing me to log in on the modified version but I'm still able to log in on the stock app 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.70.0.0.34

### SnapEnhance Version

1.2.5

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by sestuff** [comment] 2024-01-27 17:59
Duplicate of #544

**Closed** 2024-01-27 18:24 UTC
Labels: bug
