### ISSUE TITLE
Friends are unable to save snaps in chat if sent from camera roll as snap.

### ISSUE THREAD

**Issue by Itsaman27** [rhunk/SnapEnhance#394] opened 2023-11-11 13:35 UTC
### Description

My friends are unable to save the snaps in chat if I sent from the camera roll also when I edit the snap like make the size smaller or add time it didn't go.. it goes the same as gallery once... I think it's a glitch or bug please fix it in the upcoming update

### Reproduction steps

...

### Snapchat Version

12.59.0.62

### Agreement

- [X] I am using the latest stable SnapEnhance version.
- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment] 2023-11-11 13:40
Duplicate of #61

**Closed by authorisation** 2023-11-11 13:40 UTC
Labels: bug, duplicate

**Comment by Itsaman27** [comment] 2023-11-11 13:52
What about the second issue ?
