### ISSUE TITLE
SnapchatPlus

### ISSUE THREAD

**Issue by hakemdamer222** [rhunk/SnapEnhance#621] opened 2024-01-26 06:34 UTC
### Description

I'am facing a bug called "failed to init SnapchatPlus feature"

### Reproduction steps

1. Just when you open snapchat
2. With SnapchatPlus feature turned on
3. Its gonna show this message

### Snapchat Version

12.70.0.34

### SnapEnhance Version

1.2.5

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment] 2024-01-26 07:18
Duplicate of https://github.com/rhunk/SnapEnhance/issues/618

**Closed by rhunk** 2024-01-26 07:18 UTC
Labels: bug
