### ISSUE TITLE
Bug: Messages marked as Unread, even when read

### ISSUE THREAD

**Issue by yug-sid** [rhunk/SnapEnhance#686] opened 2024-02-17 10:45 UTC
### Description

Even when opening up the chat to read the unread messages, the messages are still marked as unread even after I do this. A restart and an attempted optimisation of the app have not fixed this. I have patched the application using lspatch. 

### Reproduction steps

1. Go to `...`
2. Click on `....`
3. Scroll down to `....`
4. See error.

### Snapchat Version

12.73.0.40

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment] 2024-02-17 10:58
Duplicate of https://github.com/rhunk/SnapEnhance/issues/347

**Closed by rhunk** 2024-02-17 10:58 UTC
Labels: bug
