### ISSUE TITLE
Front & Back Custom Frame Rate Feature doesn't work anymore

### ISSUE THREAD

**Issue by suryadip2008** [rhunk/SnapEnhance#1185] opened 2024-07-30 20:04 UTC
### Description

In previous versions of Snapchat, the Front & Back Custom Frame Rate used to work but on the latest versions of Snapchat it stopped working. Not sure from which versions it stopped working but it used to work earlier.

### Reproduction steps

1. Go to `SE`
2. Click on `Features`
3. Click on `Camera`
4. Click on `Front Custom Frame Rate` or `Back Custom Frame Rate`
5. Select any FPS
6. Open Snapchat
7. Observe that the feature doesn't work.

### Snapchat Version

13.1.0.40

### SnapEnhance Version

2.1.0

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by mhamad3** [comment] 2024-08-04 17:27
For me work on old snap enhance but new version in not working fix this enhance camera please

**Comment by suryadip2008** [comment] 2024-08-04 17:49
> For me work on old snap enhance but new version in not working fix enhance camera please

Which version is it working? Could you please specify?

**Comment by authorisation** [comment] 2024-08-10 15:21
Duplicate of #348

**Closed by authorisation** 2024-08-10 15:21 UTC
Labels: bug
