### ISSUE TITLE
feat: Mass remove/block friends

### ISSUE THREAD

**Issue by yesitskiko** [rhunk/SnapEnhance#294] opened 2023-10-01 11:26 UTC
### Description

Hi, would it be possible to have a feature where you can select multiple people in your feed and remove/block them.
If this could be implemented in the official SnapEnhance it would be great.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by TheVisual** [comment] 2023-10-06 01:37
Dupe of https://github.com/rhunk/SnapEnhance/issues/171

**Closed** 2023-10-09 05:21 UTC
Labels: enhancement, low priority
