### ISSUE TITLE
Detected...

### ISSUE THREAD

**Issue by v3noom** [rhunk/SnapEnhance#1138] opened 2024-06-14 13:29 UTC
### Description

Snapchat notification 

### Reproduction steps

idk how

### Snapchat Version

latest

### SnapEnhance Version

latest

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [ ] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed necessary.
- [ ] This issue is not a duplicate.

**Comment by TheVisual** [comment] 2024-06-14 13:32
Duplicate of https://github.com/rhunk/SnapEnhance/issues/1137

**Closed** 2024-06-14 13:34 UTC
Labels: bug
