### ISSUE TITLE
Add Option to Utilize Wide-angle Camera like iOS.

### ISSUE THREAD

**Issue by r-atharv11** [rhunk/SnapEnhance#991] opened 2024-05-03 19:02 UTC
### Description

Add an option to switch to Ultrawide angle camera on snap like they have on iPhones and iOS devices. 

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment] 2024-05-03 19:10
Duplicate of #729

**Closed by authorisation** 2024-05-03 19:10 UTC
Labels: enhancement

**Comment by Tilakop** [comment] 2025-01-12 06:54
Yes please add it
