### ISSUE TITLE
feat: Notifications when friend enters the chat

### ISSUE THREAD

**Issue by xnvmx** [rhunk/SnapEnhance#726] opened 2024-03-11 02:51 UTC
### Description

A great feature would be to get notifications when someone enters the chat and how long they stay there. Something like "peek a peek", but not only when a friend swipes sideways to peek at messages - but completely enters the chat and reads it.

This could be in the form of notifications similar to "peek a peek" and/or a list with dates, times and durations that could be viewed at any time.

So that this feature doesn't overload app, there could also be an option to be able to set tracking for one or just a few people.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by rhunk** [comment] 2024-03-11 07:02
Duplicate of https://github.com/rhunk/SnapEnhance/issues/275

**Closed by rhunk** 2024-03-11 07:02 UTC
Labels: enhancement
