### ISSUE TITLE
Keep Snaps in Chat not working with Gallery Media Send Override

### ISSUE THREAD

**Issue by McFaul4** [rhunk/SnapEnhance#968] opened 2024-04-27 09:18 UTC
### Description

When having "Keep Snaps in Chat" enabled in the friend feed menu under "Chat and Notification Settings", all Snaps will stay in the chat  (kinda like a normal media) for 24 hours after being viewed. But when sending a Snaps via snapenhance's "Gallery Media Send Override" the keep Snaps in chat feature doesn't work. These Snaps will just look like others do, when the feature is off. 
It also doesn't matter of you sent the Media via Snapchats media picker or from the devices gallery.

Here is a screenshot with three Snaps:
The first one is sent with the Snapchat camera.
The second one is send with "Gallery Media Send Override" using the "Snap" option.
The third one is send with "Gallery Media Send Override" using the "savable Snap" option.
![Screenshot_20240427-105736](https://github.com/rhunk/SnapEnhance/assets/116670013/5d1e36df-8358-4748-91fb-b1a2a5ca64fb)
I hope this can be fixed and this isn't a serverside issue

### Reproduction steps

1. Activate "Keep Snaps in chat" as described above.
2. Activate "Gallery Media send override" in Snapenhance
3. Send a Media from your gallery
4. View the Snap.
5. The Snap isn't kept in the chat, like it should (because of the keep Snaps in chat feature)

### Snapchat Version

v12.81.0.44

### SnapEnhance Version

v2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment] 2024-04-27 11:20
Duplicate of #61

**Closed by authorisation** 2024-04-27 11:20 UTC
Labels: bug

**Comment by McFaul4** [comment] 2024-04-27 12:18
Sorry I'm confused, is this really a duplicate? Or just not planned?
