### ISSUE TITLE
different camera lenses

### ISSUE THREAD

**Issue by jayjayare** [rhunk/SnapEnhance#1049] opened 2024-05-20 01:09 UTC
### Description

add an ability to force Snapchat to switch camera lenses on other androids, this could also be done by integrating the camera app on an android over Snapchat , this could be useful if you wanna use a wide angle view 

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment] 2024-05-20 14:16
Duplicate of #729

**Closed by authorisation** 2024-05-20 14:16 UTC
Labels: enhancement
