### ISSUE TITLE
Failed to init feature SnapchatPlus

### ISSUE THREAD

**Issue by IamNickerson** [rhunk/SnapEnhance#633] opened 2024-01-28 17:32 UTC
### Description

Hi I have a bug or its probably with me having the snapchat plus subscription but apparently it shows when enabling the snapchat plus tweak and reopening the app it shows a popup message saying Failed to init feature Snapchatplus. This happened on this snapenhance version and the previous one with the build 12.70.0.34
![Screenshot_20240128_212104_Snapchat](https://github.com/rhunk/SnapEnhance/assets/61643704/d4c6c947-f92d-4d17-a733-5ac2f58afd78)

### Reproduction steps

1. Go to `Snapenhance settings in Snapchat`
2. Scroll down to ` UI & Tweaks`
3. Click on`Snapchat Plus`
4. Reopen the app
5. The error popup will appear.

### Logs

```markdown
How i am suppose to get the logs :(
```

### Snapchat Version

12.70.0.34

### SnapEnhance Version

12.5 and 12.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by sestuff** [comment] 2024-01-28 17:46
Duplicate of #618

**Comment by IamNickerson** [comment] 2024-01-28 17:48
Am in trouble for plagiarism?

**Comment by sestuff** [comment] 2024-01-28 17:54
> Am in trouble for plagiarism?

No, just close this and make sure to check for duplicate issues before opening a new one.

**Closed** 2024-01-28 17:55 UTC
Labels: bug
