### ISSUE TITLE
Can't type on snaps...

### ISSUE THREAD

**Issue by RyanC05** [rhunk/SnapEnhance#793] opened 2024-03-31 21:45 UTC
### Description

When I take a snap and try out text over it, it shows as if it's there but when I send it, the person that receives it just sees the snap without any text

### Reproduction steps

Type text on a snap and send it

### Snapchat Version

12.79.0.37

### SnapEnhance Version

1.2.6

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by rhunk** [comment] 2024-03-31 22:01
Duplicate of https://github.com/rhunk/SnapEnhance/issues/303

**Closed by rhunk** 2024-03-31 22:01 UTC
Labels: bug
