### ISSUE TITLE
feat: Toggle to remove "Streak ended" notification.

### ISSUE THREAD

**Issue by gk98s** [rhunk/SnapEnhance#363] opened 2023-10-30 15:01 UTC
### Description

I swear since snapchat implemented this feature its been my least favourite thing about the app and it doesnt even go away in 1 click and it tries to make me pay to restore my streak I just want to see my chats normally.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by authorisation** [comment] 2023-10-30 16:50
Duplicate of #309

**Closed by authorisation** 2023-10-30 16:50 UTC
Labels: enhancement
