### ISSUE TITLE
Mutual friends and online detection

### ISSUE THREAD

**Issue by jerry-619** [rhunk/SnapEnhance#594] opened 2024-01-19 18:08 UTC
### Description

Add an option to view the mutual friends of someone who added me.

2. Add an option to know who is online right now.

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by TheVisual** [comment] 2024-01-19 20:06
Seems Similar to https://github.com/rhunk/SnapEnhance/issues/275

**Comment by rhunk** [comment] 2024-01-19 20:57
Duplicate of https://github.com/rhunk/SnapEnhance/issues/527

**Closed** 2024-01-19 20:57 UTC
Labels: enhancement
