### ISSUE TITLE
No tekst on photo and video snap.

### ISSUE THREAD

**Issue by MacCrutzen** [rhunk/SnapEnhance#638] opened 2024-01-29 10:30 UTC
### Description

When I send an photo or video with tekst I van see the tekst as normal before I send it. But the other person doesn't see any tekst and when i use the preview feature on the snap I send the tekst is also gone.

### Reproduction steps

1. Open Snapchat
2. Make a photo or video
3. Add tekst 
4. Send 
5. Tekst is gone for my self with the preview feature and the person I send it to also has no tekst 

### Snapchat Version

12.70.0.34

### SnapEnhance Version

1.2.6

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment] 2024-01-29 14:49
Duplicate of #520

**Closed by authorisation** 2024-01-29 14:49 UTC
Labels: bug
