### ISSUE TITLE
Timeout Issue

### ISSUE THREAD

**Issue by ZorgoCrypton** [rhunk/SnapEnhance#979] opened 2024-04-30 07:49 UTC
### Description

Snapchat doesn't open and shows the following issue:
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1862)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1997)
	at me.rhunk.snapenhance.core.bridge.BridgeClient.connect(Unknown Source:150)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:7)
	at me.rhunk.snapenhance.core.SnapEnhance$1.invoke(SourceFile:1)
	at me.rhunk.snapenhance.core.util.hook.Hooker$hook$$inlined$hook$1.beforeHookedMethod(Unknown Source:12)
	at q.u.fqWtlIRPLXQfvFc.do.XposedBridge$LegacyApiSupport.handleBefore(Unknown Source:24)
	at J.callback(Unknown Source:179)
	at LSPHooker_.attach(Unknown Source:11)
	at android.app.Instrumentation.newApplication(Unknown Source:12)
	at android.app.LoadedApk.makeApplicationInner(Unknown Source:174)
	at android.app.LoadedApk.makeApplicationInner(Unknown Source:1)
	at android.app.ActivityThread.handleBindApplication(Unknown Source:992)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(Unknown Source:878)
	at android.os.Handler.dispatchMessage(Unknown Source:19)
	at android.os.Looper.loopOnce(Unknown Source:182)
	at android.os.Looper.loop(Unknown Source:82)
	at android.app.ActivityThread.main(Unknown Source:123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:312)

### Reproduction steps

1. Open Snapchat
2. Get stuck at splash screen
3. See error.

### Snapchat Version

12.83.0.37

### SnapEnhance Version

2.0.1

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed necessary.
- [X] This issue is not a duplicate.

**Comment by bocajthomas** [comment] 2024-04-30 09:23
Duplicate of #978

**Closed** 2024-04-30 09:23 UTC
Labels: bug, duplicate
