### ISSUE TITLE
Bulk remove people

### ISSUE THREAD

**Issue by KaizenWRLD** [rhunk/SnapEnhance#415] opened 2023-11-17 00:50 UTC
### Description

being able to remove multiple people at once

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by TheVisual** [comment] 2023-11-18 04:21
DUPE OF https://github.com/rhunk/SnapEnhance/issues/171

Was closed at NOT Planned so.... Prob not likely

**Closed** 2023-11-18 15:52 UTC
Labels: enhancement
