### ISSUE TITLE
Message translator(hopefully)

### ISSUE THREAD

**Issue by robinbood** [rhunk/SnapEnhance#1307] opened 2024-12-07 04:37 UTC
### Description

caan you add messaage translator to it..like dev4mod did it with his whatsappenancer..(he added google-translator)

### Agreement

- [X] There is no issue already suggesting my feature.

**Comment by suryadip2008** [comment] 2024-12-07 06:20
> ### Description
> caan you add messaage translator to it..like dev4mod did it with his whatsappenancer..(he added google-translator)
> 
> ### Agreement
> * [x]  There is no issue already suggesting my feature.

Duplicate of https://github.com/rhunk/SnapEnhance/issues/1114

**Closed** 2024-12-07 09:10 UTC
Labels: enhancement
