### ISSUE TITLE
Message Indicators

### ISSUE THREAD

**Issue by BubbaKel** [rhunk/SnapEnhance#868] opened 2024-04-10 14:48 UTC
### Description

The message indicators (lock icon, phone type, location, etc) don't stay on the snap if the option "Keep Snaps in Chat" is enabled. If it isn't enabled, they stay with the message, if it is enabled then they don't stay.

### Reproduction steps

Go to "Chat Settings" by clicking and holding on a chat. Either have the option "Keep Snaps in chat" enabled or disabled. 
- Enabled = No icon after opening snap
- Disabled = Icon stays after opening

### Snapchat Version

Newest

### SnapEnhance Version

Newest

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by authorisation** [comment] 2024-04-10 16:54
I can't reproduce this issue. Did you turn on anything else?

**Comment by BubbaKel** [comment] 2024-04-10 17:56
No. I even turned that setting off to see if it was that and it is. If it's enabled and you receive a snap, it won't have the icons after uts opened. If you don't have it enabled, it will show after it's opened.

**Comment by BubbaKel** [comment] 2024-04-10 17:56
I just want it to be fixed and have that added

**Comment by authorisation** [comment] 2024-04-10 18:04
Share your SE config

**Comment by BubbaKel** [comment] 2024-04-10 18:09
How do I do that

**Comment by authorisation** [comment] 2024-04-10 20:45
Refer to this: https://github.com/rhunk/SnapEnhance/issues/870#issuecomment-2048060980

**Comment by bocajthomas** [comment] 2024-04-11 01:00
> I can't reproduce this issue. Did you turn on anything else?

Tried reproducing Too And it works 

@BubbaKel make sure your on Ether Snapchat Stable `V12.79` or `12.80`

And make sure you have `V2.0.0` Stable Release

**Comment by BrokenOG** [comment] 2024-04-11 10:17
> ### Description
> 
> The message indicators (lock icon, phone type, location, etc) don't stay on the snap if the option "Keep Snaps in Chat" is enabled. If it isn't enabled, they stay with the message, if it is enabled then they don't stay.
> 
> ### Reproduction steps
> 
> Go to "Chat Settings" by clicking and holding on a chat. Either have the option "Keep Snaps in chat" enabled or disabled. 
> - Enabled = No icon after opening snap
> - Disabled = Icon stays after opening
> 
> ### Logs
> 
> _No response_
> 
> ### Snapchat Version
> 
> Newest
> 
> ### SnapEnhance Version
> 
> Newest
> 
> ### Agreement
> 
> - [X] This is not a bug regarding Snapchat+.
> - [X] I have provided a detailed description of the issue.
> - [X] I have attached a log if deemed neccessary.
> - [X] This issue is not a duplicate.

It can be solved when the snap stays for 24 hrs the indicators get merged on the top right of the border of snap and are severely visible you can save the snap and then unsave it in my case it helped me hope it may help in your case too.

**Comment by BubbaKel** [comment] 2024-04-11 13:28
> > I can't reproduce this issue. Did you turn on anything else?
> 
> Tried reproducing Too And it works
> 
> @BubbaKel make sure your on Ether Snapchat Stable `V12.79` or `12.80`
> 
> And make sure you have `V2.0.0` Stable Release

How do I check the snap version? I checked the SnapEnhance version and I downloaded v2

**Comment by bocajthomas** [comment] 2024-04-11 15:22
> How do I check the snap version? I checked the SnapEnhance version and I downloaded v2

<details closed>
  <summary>How To Check</summary>

1. Open Snapchat 
2. Tap Your Profile
3. Tap The Gear Settings 
4. Scroll Down To The Very Bottom 
5. You will see Snapchat v xx.xx.x.xx 

</details>

**Comment by achyutde13** [comment] 2024-04-11 19:42
I have the same issue, the lock icon was green for me and it dissappears with the 'keep snaps in chat' enabled.

**Comment by BrokenOG** [comment] 2024-04-12 15:09
> If anyone could send a video of how to reproduce the issue that would help thank you

I tried to recreate this issue but it seems like this issue is just in this users device i tried recreation on 3 devices but the feature worked fine

**Comment by authorisation** [comment] 2024-04-12 19:14
Closing this as it seems not reproducible, considering the issue itself is formatted incorrectly I don't know why I even accepted this in the first place.

**Closed by authorisation** 2024-04-12 19:14 UTC
Labels: bug, question
