### ISSUE TITLE
Snapchat+ spoofer is broken

### ISSUE THREAD

**Issue by KaitlynnKitten** [rhunk/SnapEnhance#634] opened 2024-01-28 18:09 UTC
### Description

![Capture+_2024-01-28-12-01-09](https://github.com/rhunk/SnapEnhance/assets/139692158/bf507783-5b9f-4fb2-b3c9-e8147764d767)
Snapchat plus doesn't work and shows up with error "Failed to init feature SnapchatPlus" error will display upon Snapchat launch or just randomly

### Reproduction steps

1. open Snapchat with Snapchat plus mod enabled 

### Snapchat Version

12.70.0.34

### SnapEnhance Version

1.2.6

### Agreement

- [ ] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [ ] I have attached a log if deemed neccessary.
- [ ] This issue is not a duplicate.

**Comment by SirenGlitch** [comment] 2024-01-28 18:29
Confirming this, started recently in 1.2.5, still happening in 1.2.6

**Comment by Yoganshbhatt** [comment] 2024-01-28 18:39
Yes it has been there for a couple of days maybe now. Constant notifications popping and also the app crashes wierdly on opening chats from notifications

**Comment by sestuff** [comment] 2024-01-28 19:00
Duplicate of #618 

If you had looked at previous issues before making this, you would've seen that the solution right now is updating to v2 or waiting for a v1 fix. The agreement to make an issue also literally says "This is not a bug regarding Snapchat+".

**Comment by rhunk** [comment] 2024-01-28 19:19
refreshing mappings should fix

**Closed by rhunk** 2024-01-28 19:19 UTC
Labels: bug

**Comment by SirenGlitch** [comment] 2024-01-28 19:24
> refreshing mappings should fix

Where do you do that? I don't see a button

**Comment by Yoganshbhatt** [comment] 2024-01-28 19:30
> Duplicate of #618
> 
> If you had looked at previous issues before making this, you would've seen that the solution right now is updating to v2 or waiting for a v1 fix. The agreement to make an issue also literally says "This is not a bug regarding Snapchat+".
Thanks mate! The new ui and everything looks dope! Idk if the stock camera quality will be possible for my snaps or not but everything else works great!
