### ISSUE TITLE
Snapchat not letting me log in

### ISSUE THREAD

**Issue by Oszmi** [rhunk/SnapEnhance#620] opened 2024-01-26 00:46 UTC
### Description

When I try to log in with snapenhance installed, it doesn't let me log in it says that I did too many tries or other activities. Version 1.2.5

### Reproduction steps

1. Go to snapchat 
2. Click on already have an account 
3. Put in your log in informations
4. See error.

### Logs

```markdown
Failed to get scripts folder
Loading RemoteSideContext
```

### Snapchat Version

12.70.0.30

### SnapEnhance Version

1.2.5

### Agreement

- [X] This is not a bug regarding Snapchat+.
- [X] I have provided a detailed description of the issue.
- [X] I have attached a log if deemed neccessary.
- [X] This issue is not a duplicate.

**Comment by rhunk** [comment] 2024-01-26 07:45
Duplicate of https://github.com/rhunk/SnapEnhance/issues/544

**Closed by rhunk** 2024-01-26 07:45 UTC
Labels: bug
